### ISSUE TITLE
设置请求

### ISSUE THREAD

**Issue by Xqshyg** [SubConv/ZJU-Rule#2]
copilot好像没走chatbot导致rule的时候访问不了，大佬可以设置一下吗？

**Comment by wouiSB** [comment]
你说的是Microsolf Copilot还是GitHub Copilot

**Comment by Xqshyg** [comment]
> 你说的是Microsolf Copilot还是GitHub Copilot

Microsoft的

**Comment by wouiSB** [comment]
在微软bing分组里

**Comment by Xqshyg** [comment]
噢噢，看到了，谢谢您!

**Comment by razgzy** [comment]
github copilot在隐私防护列表里直接reject了，应该要修改一下
DOMAIN-SUFFIX,copilot-telemetry.githubusercontent.com

**Comment by wouiSB** [comment]
你用的是哪个配置文件

**Comment by razgzy** [comment]
> 你用的是哪个配置文件

https://raw.githubusercontent.com/SubConv/ZJU-Rule/main/Clash/config/ZJU.ini

**Comment by wouiSB** [comment]
但是这个被reject有什么影响呢
根据 [文档](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot) ，这个域名应该只是用来遥测的，reject不应该导致无法使用吧

**Comment by razgzy** [comment]
vscode里的copilot插件会被影响，我vscode里ssh服务器用的时候，服务器的clash加了这条规则我就连不上copilot，clash日志里就显示了这一条

**Comment by wouiSB** [comment]
个人在试用的时候没有遇到过这个情况，建议区上游提issue
https://github.com/ACL4SSR/ACL4SSR/issues
